apiVersion: v1
kind: Pod
metadata:
  name: pod-configmap
spec:
  containers:
    - name: nginx
      image: nginx
      envFrom:
      - configMapRef:
          name: configmap
      # env:
      # - name: course
      #   valueFrom:
      #     configMapKeyRef:
      #       name: configmap
      #       key: course
      # - name: trainer
      #   valueFrom:
      #     configMapKeyRef:
      #       name: configmap
      #       key: trainer
